import type { NormalizedState, Role } from './types';

// ---- Pruned static data (generated by scripts/gen-coach-data.mjs) ----
export interface AbilityData {
  dname: string;
  dmgType?: 'Magical' | 'Physical' | 'Pure';
  bkbPierce?: 'Yes' | 'No';
  dispellable?: 'Yes' | 'No' | 'Strong Dispels Only';
  targetTeam?: 'Enemy' | 'Friendly' | 'Both';
  behavior?: string[];
  cd?: number[];
  mc?: number[];
  attribs?: { key: string; header: string; value: number[] }[];
  isInnate?: boolean;
}

export interface HeroData {
  name: string; // npc_dota_hero_*
  localizedName: string;
  attackType: string; // 'Melee' | 'Ranged'
  roles: string[];
  abilities: string[]; // keys into AbilityDataMap
}

export interface ItemData {
  dname: string;
  cost: number;
  components?: string[];
}

export type AbilityDataMap = Record<string, AbilityData>;
export type HeroDataMap = Record<string, HeroData>; // keyed by numeric hero id as string
export type ItemDataMap = Record<string, ItemData>; // keyed by dotaconstants item key (no 'item_' prefix)

// ---- Threat report (threats.ts) ----
export type ThreatKind =
  | 'magical-burst'      // magical nuke that BKB blocks
  | 'pierces-bkb'        // damage/control that goes through BKB
  | 'dispellable-debuff' // basic dispel removes it
  | 'strong-dispel-debuff'
  | 'undispellable'
  | 'hard-disable'       // hex/stun-like control
  | 'silence'
  | 'invisibility'
  | 'evasion'
  | 'illusions'
  | 'summons'
  | 'sustain';           // heavy healing/lifesteal

export interface ThreatFlag {
  kind: ThreatKind;
  heroId: number;
  heroName: string;      // localized
  abilityName: string;   // display name of the offending ability
  targeted?: boolean;    // single-unit-targeted (relevant for Linken's-style counters)
}

export interface ThreatReport {
  enemies: { heroId: number; heroName: string }[];
  flags: ThreatFlag[];
  counts: Partial<Record<ThreatKind, number>>;
}

// ---- Item recommendations (items.ts) ----
export interface ItemRecommendation {
  itemKey: string;   // dotaconstants key, e.g. 'black_king_bar'
  itemName: string;  // display name
  cost: number;
  affordable: boolean;
  score: number;
  reasons: string[]; // human explanations citing enemy heroes/abilities
}

export interface ItemEngineInput {
  threat: ThreatReport;
  role: Role;
  gold: number | null;
  clock: number | null;
  ownedItems: string[];  // GSI names, incl. 'item_' prefix
  attackType?: string;   // own hero's attack type
}

// ---- Skill readout (skills.ts) ----
export interface SkillReadout {
  key: string;
  name: string;
  level: number;
  maxLevel: number;
  damage: number | null;     // primary damage at current level
  damageNext: number | null; // damage at next level (what one more point buys)
  dmgType: string | null;
  cooldown: number | null;          // static cd at current level
  remainingCooldown: number | null; // live from GSI
  manaCost: number | null;
  canCast: boolean | null;
  ultimate: boolean;
  passive: boolean;
}

// ---- Coach tips (coach.ts) ----
export interface CoachTip {
  id: string; // stable id, e.g. 'unspent-gold'
  severity: 'info' | 'warn' | 'urgent';
  message: string;
}

export interface CoachInput {
  state: NormalizedState;
  role: Role;
  threat: ThreatReport | null;
}
