import { describe, it, expect } from 'vitest';
import { HERO_DATA, ITEM_DATA, HERO_BUILDS, DATA_META } from './data';

describe('hero-builds.json integrity (generated by gen-hero-builds.mjs)', () => {
  it('covers every hero with a valid fun pool', () => {
    const heroIds = new Set(Object.keys(HERO_DATA));
    for (const [id, build] of Object.entries(HERO_BUILDS)) {
      expect(heroIds.has(id), `hero id ${id} not in hero-data`).toBe(true);
      expect(build.fun.length, `hero ${id} pool too small`).toBeGreaterThanOrEqual(6);
      for (const item of build.fun) {
        expect(ITEM_DATA[item.key], `hero ${id}: unknown item key ${item.key}`).toBeDefined();
        expect(item.name).not.toBe('');
      }
    }
    // Every hero has a pool (regen with `pnpm gen-hero-builds` if this fails).
    expect(Object.keys(HERO_BUILDS).length).toBe(Object.keys(HERO_DATA).length);
  });
});

describe('data-meta', () => {
  it('records the data provenance', () => {
    expect(DATA_META.source).toBe('dotaconstants');
    expect(DATA_META.gamePatch).toMatch(/^\d+\.\d+/);
  });
});
