import type { AbilityDataMap, HeroBuildsMap, HeroDataMap, ItemDataMap } from './coaching-types';
import heroDataJson from './data/hero-data.json';
import abilityDataJson from './data/ability-data.json';
import itemDataJson from './data/item-data.json';
import heroBuildsJson from './data/hero-builds.json';
import dataMetaJson from './data/data-meta.json';

export const HERO_DATA = heroDataJson as HeroDataMap;
export const ABILITY_DATA = abilityDataJson as AbilityDataMap;
export const ITEM_DATA = itemDataJson as ItemDataMap;
/** LLM-curated per-hero fun item pools (generated by scripts/gen-hero-builds.mjs). */
export const HERO_BUILDS = heroBuildsJson as HeroBuildsMap;
/** Provenance of the generated data (dotaconstants version + game patch). */
export const DATA_META = dataMetaJson as { source: string; version: string; gamePatch: string };

export function heroById(id: number | null): HeroDataMap[string] | null {
  if (id === null) return null;
  return HERO_DATA[String(id)] ?? null;
}
